version: "3"
services:
  natural-identifiers-database:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: natural-identifiers-database
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword1
    ports:
      - 1400:1433