IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Order')
BEGIN
	CREATE TABLE [dbo].[Order] (
		[Id] [bigint] IDENTITY(1,1) NOT NULL,
		[Description] [nvarchar](max) NOT NULL,
		[Customer_FirstName] [nvarchar](max) NULL,
		[Customer_LastName] [nvarchar](max) NULL,
	 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END